### PR TITLE
Allow heredoc on assert_output and refute_output

### PR DESCRIPTION
**Pull request by juanibiapina**
This allows assertions with the format:

```
assert_output <<OUTPUT
line 1
line 2
OUTPUT
```

### CODE REVIEW

**Comment by ztombol** [comment]
This is a good idea. It's a good start but you are missing a few things. Most of these you wil find in the Standard Library roposal. This feature was part of it for a while before being taken out in https://github.com/ztombol/bats/commit/35923445e1222d2236d1c5025c077674ee3b5b63 (nobody thought about heredocs at the time). You can probably copy-paste with minimal adaptation.

I didn't have the time yet, but I've been wanting to add contribution guidlines that spell out code conventions explicitly and make life easier. For now, here's what I was thinking.

### Code
- Error handling for arguments and parameters ([example](https://github.com/ztombol/bats/commit/35923445e1222d2236d1c5025c077674ee3b5b63#diff-a4a9342428b65e174f64a591f29791feL145))
- Use [arithmetic evaluation](http://wiki.bash-hackers.org/syntax/ccmd/arithmetic_eval) when testing integers in conditions.
- When in doubt, look at the other functions.

``` bash
if (( $# == 0 )); then
  ...
else
  ...
fi
```

### Documentation
- Add user documentation in `README.md` ([example](https://github.com/ztombol/bats/commit/35923445e1222d2236d1c5025c077674ee3b5b63#diff-04c6e90faac2675aa89e2176d2eec7d8L444)).
- Add developer documentation in the function comments ([example](https://github.com/ztombol/bats/commit/35923445e1222d2236d1c5025c077674ee3b5b63#diff-a4a9342428b65e174f64a591f29791feL99)).
- When in doubt, look at the other functions.

### Tests
- The description consists of two parts, `<interface>: <expected result>`.
- Descriptions should use strong quotation when possible.
- Tests are executed in a special order. First, test the core logic (fail and success). Then, test options and interface variations. So the new test should go after the two existing. For example:

```
# Correctness
@test "assert_output() <expected>: returns 0 if <expected> equals \`\$output'" {
  ...
}

@test "assert_output() <expected>: returns 1 and displays details if <expected> does not equal \`\$output'" {
  ...
}

@test 'assert_output(): reads <expected> from STDIN' {
  ...
}

# Output formatting
```
- When in doubt, look at the other functions.

Thanks!

**Comment by juanibiapina** [comment]
I have made the suggested changes, except for 'Error handling for arguments and parameters'. I believe that is a feature by itself which could go in a different pull request.

The only place where the code differed from the previous one is here: https://github.com/juanibiapina/bats-assert/blob/heredoc/test/50-assert-15-assert_output.bats#L31 . It's easier to use a heredoc here instead of the original code: https://github.com/ztombol/bats/commit/35923445e1222d2236d1c5025c077674ee3b5b63#diff-444ffab6897d468d0a0705a244cecb95L67

I also squashed everything in one commit. It's a simple enough change.

**Comment by ztombol** [comment]
You're right. Error handling is big and messy enough to be in its separate pull request. Nice and clean patch. Thanks you!

**Comment by juanibiapina** [comment]
With this change, basher now uses bats-assert: https://github.com/basherpm/basher/commit/8bb692017ab5dfb1bbc18f0afdcbbe6b97bb581f

**Comment by ztombol** [comment]
Thanks! I'll make sure to include basher in the _list of projects using these helper libraries_ when I get around writing it (hopefully mid-late next week).

**Pull request merged**
